//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobasco.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GenericRepositoryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericRepositoryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobasco.Properties.GenericRepositoryResources", typeof(GenericRepositoryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public IEnumerable&lt;T&gt; Save(IEnumerable&lt;T&gt; entities)
        ///{
        ///	var enumerable = entities as IList&lt;T&gt; ?? entities.ToList();
        ///	foreach (var entity in enumerable)
        ///	{
        ///		Save(entity);
        ///	}
        ///	return enumerable;
        ///}.
        /// </summary>
        internal static string GenericRepositoryBulkSave {
            get {
                return ResourceManager.GetString("GenericRepositoryBulkSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public void Delete(T entity)
        ///{
        ///	using (var connection = ConnectionFactory.GetConnection())
        ///	{
        ///		connection.Execute($&quot;[dbo].[{ typeof(T).Name}_Delete]&quot;,
        ///			new {entity.Id, entity.RowVersion, entity.ModifiedBy },
        ///			commandType: CommandType.StoredProcedure);
        ///	}
        ///}.
        /// </summary>
        internal static string GenericRepositoryDelete {
            get {
                return ResourceManager.GetString("GenericRepositoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public T GetById(long id)
        ///{
        ///	T entity;
        ///	using (var connection = ConnectionFactory.GetConnection())
        ///	{
        ///		entity = connection.QuerySingle&lt;T&gt;($&quot;[dbo].[{ typeof(T).Name}_GetById]&quot;,
        ///			new {Id = id},
        ///			commandType: CommandType.StoredProcedure);
        ///	}
        ///	entity.MarkOld();
        ///	return entity;
        ///}.
        /// </summary>
        internal static string GenericRepositoryGetById {
            get {
                return ResourceManager.GetString("GenericRepositoryGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public T Insert(T entity)
        ///{
        ///	using (var connection = ConnectionFactory.GetConnection())
        ///	{
        ///		connection.Query&lt;long, byte[], T&gt;($&quot;[dbo].[{typeof(T).Name}_Insert]&quot;, (id, rowversion) =&gt;
        ///		{
        ///			entity.Id = id;
        ///			entity.RowVersion = rowversion;
        ///			return entity;
        ///		}, ToAnonymous(entity, false), splitOn: &quot;RowVersion&quot;, commandType: CommandType.StoredProcedure);
        ///	}
        ///	entity.MarkOld();
        ///	return entity;
        ///}.
        /// </summary>
        internal static string GenericRepositoryInsert {
            get {
                return ResourceManager.GetString("GenericRepositoryInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public IEnumerable&lt;T&gt; QueryMultiple(string StoredProcedure, DynamicParameters parameters, Func&lt;GridReader, IEnumerable&lt;T&gt;&gt; readerFunc)
        ///        {
        ///            using (var connection = ConnectionFactory.GetConnection())
        ///            {
        ///                return readerFunc(connection.QueryMultiple(StoredProcedure, parameters, commandType: CommandType.StoredProcedure));
        ///            }
        ///        }.
        /// </summary>
        internal static string GenericRepositoryQueryMultipleT {
            get {
                return ResourceManager.GetString("GenericRepositoryQueryMultipleT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public T Save(T entity)
        ///{
        ///	if(entity.IsDeleted)
        ///	{
        ///		Delete(entity);
        ///		return entity;
        ///	}
        ///	if(entity.IsNew)
        ///	{
        ///		return Insert(entity);
        ///	}
        ///	if(entity.IsDirty)
        ///	{
        ///		return Update(entity);
        ///	}
        ///	return entity;
        ///}.
        /// </summary>
        internal static string GenericRepositorySave {
            get {
                return ResourceManager.GetString("GenericRepositorySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private DynamicParameters ToAnonymous(T entity, bool includeRowVersion)
        ///{
        ///	dynamic anonymousEntity = entity.ToAnonymous();
        ///	anonymousEntity.Id = entity.Id;
        ///	var parameters = new DynamicParameters(anonymousEntity);
        ///	if (includeRowVersion)
        ///	{
        ///		parameters.Add(&quot;RowVersion&quot;, entity.RowVersion, DbType.Binary);
        ///	}
        ///	return parameters;
        ///}.
        /// </summary>
        internal static string GenericRepositoryToAnonymous {
            get {
                return ResourceManager.GetString("GenericRepositoryToAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public T Update(T entity)
        ///{
        ///	using (var connection = ConnectionFactory.GetConnection())
        ///	{
        ///		try
        ///		{
        ///			entity.RowVersion = connection.ExecuteScalar&lt;byte[]&gt;($&quot;[dbo].[{ typeof(T).Name}_Update]&quot;,
        ///				ToAnonymous(entity, true),
        ///				commandType: CommandType.StoredProcedure);
        ///		}
        ///		catch(SqlException ex)
        ///		{
        ///			if (ex.Number == 50000 &amp;&amp; ex.Class == 16 &amp;&amp; ex.Message.Contains(&quot; is al gewijzigd door een andere gebruiker.&quot;))
        ///			{
        ///				throw new DBConcurrencyException($&quot;Dirty write detected while updatin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericRepositoryUpdate {
            get {
                return ResourceManager.GetString("GenericRepositoryUpdate", resourceCulture);
            }
        }
    }
}
