//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobasco.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RepositoryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RepositoryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobasco.Properties.RepositoryResources", typeof(RepositoryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RepositoryGetById {
            get {
                return ResourceManager.GetString("RepositoryGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal static Dictionary&lt;long, %EntityName%&gt; Read(GridReader reader)
        ///{
        ///	%ChildReader%
        ///	
        ///	%ChildCollectionReader%
        ///
        ///    var items = reader.Read((%ReaderParameters%) =&gt;
        ///    {
        ///        %ChildReadDictionary%
        ///
        ///        %ChildCollectionReadDictionary%
        ///
        ///        return item;
        ///    }, splitOn: &quot;%SplitOn%&quot;);
        ///
        ///    return items.ToDictionary(x =&gt; x.Id);        
        ///}.
        /// </summary>
        internal static string RepositoryGetFullByIdReader {
            get {
                return ResourceManager.GetString("RepositoryGetFullByIdReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal static Dictionary&lt;long, %EntityName%&gt; Read(GridReader reader)
        ///{
        ///    return reader.Read&lt;%EntityName%&gt;().ToDictionary(x =&gt; x.Id);      
        ///}.
        /// </summary>
        internal static string RepositoryGetFullByIdReaderWithoutProp {
            get {
                return ResourceManager.GetString("RepositoryGetFullByIdReaderWithoutProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public %EntityName% GetFullObjectById(long id)
        ///{
        ///    var parameters = new DynamicParameters();
        ///    parameters.Add(&quot;id&quot;, id);
        ///    return _genericRepository.ExecuteQueryMultiple(&quot;%GetByIdStp%&quot;, parameters, x =&gt; Read(x).Values).SingleOrDefault();
        ///}.
        /// </summary>
        internal static string RepositoryGetFullObjectById {
            get {
                return ResourceManager.GetString("RepositoryGetFullObjectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public %EntityName% GetFullObjectByUId(Guid uid)
        ///{
        ///    var parameters = new DynamicParameters();
        ///    parameters.Add(&quot;UId&quot;, uid);
        ///    return _genericRepository.ExecuteQueryMultiple(&quot;%GetByUIdStp%&quot;, parameters, x =&gt; Read(x).Values).SingleOrDefault();
        ///}.
        /// </summary>
        internal static string RepositoryGetFullObjectByUId {
            get {
                return ResourceManager.GetString("RepositoryGetFullObjectByUId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal static Dictionary&lt;long, %EntityName%&gt; Read(GridReader reader)
        ///{
        ///	%ChildReader%
        ///	
        ///	%ChildCollectionReader%
        ///
        ///    var items = reader.Read((%EntityName% item, %EntityName% returnItem) =&gt;
        ///    {
        ///        %ChildCollectionReadDictionary%
        ///
        ///        return returnItem;
        ///    });
        ///
        ///    return items.ToDictionary(x =&gt; x.Id);        
        ///}.
        /// </summary>
        internal static string RepositoryGetFullyByIdChildCollectionReader {
            get {
                return ResourceManager.GetString("RepositoryGetFullyByIdChildCollectionReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public %EntityName% Save(%EntityName%  %EntityNameLowerCase%)
        ///{
        ///	%SaveChild%	
        ///	%EntityNameLowerCase% = _genericRepository.Save(%EntityNameLowerCase%);	
        ///	%SaveChildCollections%	
        ///	return %EntityNameLowerCase%;
        ///}.
        /// </summary>
        internal static string RepositorySave {
            get {
                return ResourceManager.GetString("RepositorySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public %EntityName% Save(%EntityName%  %EntityNameLowerCase%)
        ///{
        ///	using (var trans = new TransactionScope())
        ///	{
        ///		%SaveChild%		
        ///		%EntityNameLowerCase% = _genericRepository.Save(%EntityNameLowerCase%);		
        ///		%SaveChildCollections%				
        ///		trans.Complete();
        ///	}
        ///	return %EntityNameLowerCase%;
        ///}.
        /// </summary>
        internal static string RepositorySaveWithTransaction {
            get {
                return ResourceManager.GetString("RepositorySaveWithTransaction", resourceCulture);
            }
        }
    }
}
